#!/usr/bin/python2.7
from hosted import device, node, config
config.restart_on_update()

device.gpio.monitor(config.pin)
for pin, state in device.gpio.poll_forever():
    node.send('/state:%d' % state)
    print("pin touched")
